CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(40) NOT NULL,
    email VARCHAR(254) NOT NULL,
    password VARCHAR(512) NOT NULL,
    role VARCHAR(16) NOT NULL CHECK (role IN ('ADMIN', 'SELLER', 'CUSTOMER')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_username_nonempty CHECK (length(btrim(username)) > 0),
    CONSTRAINT users_email_nonempty CHECK (length(btrim(email)) > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS users_username_case_insensitive_unique ON users (LOWER(username));
CREATE UNIQUE INDEX IF NOT EXISTS users_email_case_insensitive_unique ON users (LOWER(email));

CREATE TABLE IF NOT EXISTS categories (
    category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE IF NOT EXISTS products (
    product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id INTEGER NOT NULL REFERENCES users(user_id),
    category_id INTEGER NOT NULL REFERENCES categories(category_id),
    product_name VARCHAR(200) NOT NULL,
    description TEXT,
    price NUMERIC(12, 2) NOT NULL CHECK (price > 0),
    stock_quantity INTEGER NOT NULL CHECK (stock_quantity >= 0),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS shopping_cart (
    cart_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    product_id INTEGER NOT NULL REFERENCES products(product_id) ON DELETE CASCADE,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    CONSTRAINT shopping_cart_customer_product_unique UNIQUE (customer_id, product_id)
);

CREATE TABLE IF NOT EXISTS wishlist (
    wishlist_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    product_id INTEGER NOT NULL REFERENCES products(product_id) ON DELETE CASCADE,
    CONSTRAINT wishlist_customer_product_unique UNIQUE (customer_id, product_id)
);

CREATE TABLE IF NOT EXISTS orders (
    order_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES users(user_id),
    total_amount NUMERIC(14, 2) NOT NULL CHECK (total_amount >= 0),
    order_status VARCHAR(16) NOT NULL DEFAULT 'PENDING'
        CHECK (order_status IN ('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED')),
    order_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS order_details (
    order_details_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
    product_id INTEGER NOT NULL REFERENCES products(product_id),
    seller_id INTEGER NOT NULL REFERENCES users(user_id),
    product_name VARCHAR(200) NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price > 0)
);

CREATE TABLE IF NOT EXISTS payments (
    payment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL REFERENCES orders(order_id),
    payment_status VARCHAR(16) NOT NULL CHECK (payment_status IN ('SUCCESS', 'FAILED', 'REFUNDED')),
    amount NUMERIC(14, 2) NOT NULL CHECK (amount >= 0),
    payment_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reviews (
    review_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES products(product_id),
    customer_id INTEGER NOT NULL REFERENCES users(user_id),
    rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment VARCHAR(2000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT reviews_customer_product_unique UNIQUE (customer_id, product_id)
);

CREATE INDEX IF NOT EXISTS products_category_active_price_idx ON products(category_id, active, price);
CREATE INDEX IF NOT EXISTS products_seller_idx ON products(seller_id);
CREATE INDEX IF NOT EXISTS cart_customer_idx ON shopping_cart(customer_id);
CREATE INDEX IF NOT EXISTS wishlist_customer_idx ON wishlist(customer_id);
CREATE INDEX IF NOT EXISTS orders_customer_date_idx ON orders(customer_id, order_date DESC);
CREATE INDEX IF NOT EXISTS orders_status_date_idx ON orders(order_status, order_date DESC);
CREATE INDEX IF NOT EXISTS order_details_order_idx ON order_details(order_id);
CREATE INDEX IF NOT EXISTS order_details_seller_order_idx ON order_details(seller_id, order_id);
CREATE INDEX IF NOT EXISTS payments_order_date_idx ON payments(order_id, payment_date DESC);
CREATE INDEX IF NOT EXISTS reviews_product_date_idx ON reviews(product_id, created_at DESC);
